# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.496, name: "0"},
    {id: 4, size: 1.03, name: "4"},
    {id: 73, size: 0.097, name: "73"},
    {id: 74, size: 0.097, name: "74"}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
tag_bundles:
  [
    {
      name: 'jig_big',
      layout:
        [
          {id: 0, size: 0.496, x: 1.11439, y: 0.038571, z: 0.167434, qw: 0.953327, qx: -0.0200102, qy: 0.301266, qz: -0.00266188},
          {id: 4, size: 1.03, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
        ],
      frame_id: 'jig'
    }

  ]
